// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AddPokemonEvolution(arg1:models.PokemonEvolutionRequest):Promise<void>;

export function DeletePokemonEvolution(arg1:models.PokemonEvolutionRequest):Promise<void>;

export function UpdatePokemonEvolution(arg1:models.PokemonEvolutionRequest):Promise<void>;
