// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddPokemonEvolution(arg1) {
  return window['go']['pokemoneditor']['PokemonEditorApp']['AddPokemonEvolution'](arg1);
}

export function DeletePokemonEvolution(arg1) {
  return window['go']['pokemoneditor']['PokemonEditorApp']['DeletePokemonEvolution'](arg1);
}

export function UpdatePokemonEvolution(arg1) {
  return window['go']['pokemoneditor']['PokemonEditorApp']['UpdatePokemonEvolution'](arg1);
}
