// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function ParseMoves():Promise<models.AllMoves>;

export function UpdateMove(arg1:models.UpdatedMove):Promise<void>;
