// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ParseMoves() {
  return window['go']['moveeditor']['MoveEditorApp']['ParseMoves']();
}

export function UpdateMove(arg1) {
  return window['go']['moveeditor']['MoveEditorApp']['UpdateMove'](arg1);
}
