// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateTrainerData(arg1) {
  return window['go']['main']['App']['CreateTrainerData'](arg1);
}

export function ParseHeldItems() {
  return window['go']['main']['App']['ParseHeldItems']();
}

export function ParsePokemonData() {
  return window['go']['main']['App']['ParsePokemonData']();
}

export function ParseTrainerClass() {
  return window['go']['main']['App']['ParseTrainerClass']();
}

export function ParseTrainers() {
  return window['go']['main']['App']['ParseTrainers']();
}

export function SetDataFolder() {
  return window['go']['main']['App']['SetDataFolder']();
}
