// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {models} from '../models';

export function CreateTrainerData(arg1:main.TrainerJson):Promise<void>;

export function ParseHeldItems():Promise<Array<main.HeldItem>>;

export function ParsePokemonData():Promise<Array<main.PokemonTrainerEditor>>;

export function ParseTrainerClass():Promise<models.TrainerClasses>;

export function ParseTrainers():Promise<models.TrainerToml>;

export function SetDataFolder():Promise<void>;
