// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateMap(arg1) {
  return window['go']['mapeditor']['MapEditorApp']['CreateMap'](arg1);
}

export function CreateTileset(arg1) {
  return window['go']['mapeditor']['MapEditorApp']['CreateTileset'](arg1);
}

export function CreateTilesetImage(arg1) {
  return window['go']['mapeditor']['MapEditorApp']['CreateTilesetImage'](arg1);
}

export function DeleteMapByID(arg1) {
  return window['go']['mapeditor']['MapEditorApp']['DeleteMapByID'](arg1);
}

export function GetTilesetImageData(arg1) {
  return window['go']['mapeditor']['MapEditorApp']['GetTilesetImageData'](arg1);
}
