// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function CreateTileset(arg1:models.CreateNewTileset):Promise<Record<string, any>>;

export function CreateTilesetImage(arg1:string):Promise<Record<string, any>>;

export function GetTilesetImageData(arg1:string):Promise<Record<string, any>>;
