// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function CreateMap(arg1:models.MapEditerMapData):Promise<Record<string, any>>;

export function CreateTileset(arg1:models.CreateNewTileset):Promise<Record<string, any>>;

export function CreateTilesetImage(arg1:string):Promise<Record<string, any>>;

export function DeleteMapByID(arg1:number):Promise<Record<string, any>>;

export function GetTilesetImageData(arg1:string):Promise<Record<string, any>>;
