// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateMap() {
  return window['go']['mapeditor']['MapEditorApp']['CreateMap']();
}
