// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {mapeditor} from '../models';

export function ClearTileCache():Promise<Record<string, any>>;

export function CreateMap(arg1:models.MapEditerMapData):Promise<Record<string, any>>;

export function CreateTileset(arg1:models.CreateNewTileset):Promise<Record<string, any>>;

export function CreateTilesetImage(arg1:string):Promise<Record<string, any>>;

export function DeleteMapByID(arg1:number):Promise<Record<string, any>>;

export function GetPreloadProgress():Promise<Record<string, any>>;

export function GetRenderProgress():Promise<Record<string, any>>;

export function GetTilesetImageData(arg1:string):Promise<Record<string, any>>;

export function PreloadTilesOnly(arg1:Array<string>):Promise<Record<string, any>>;

export function PreloadTilesWithProgress(arg1:Array<string>,arg2:mapeditor.RenderRequest):Promise<Record<string, any>>;

export function RenameMapFile(arg1:string,arg2:string):Promise<Record<string, any>>;

export function RenderMap(arg1:mapeditor.RenderRequest):Promise<Record<string, any>>;

export function RenderMapAfterPreload(arg1:mapeditor.RenderRequest):Promise<Record<string, any>>;

export function RenderMapWithProgress(arg1:mapeditor.RenderRequest):Promise<Record<string, any>>;

export function StampTile(arg1:mapeditor.StampRequest):Promise<mapeditor.StampResponse>;

export function UpdateMapJson(arg1:models.MapJsonData):Promise<Record<string, any>>;

export function UpdateMapJsonWithPath(arg1:models.MapJsonData,arg2:string):Promise<Record<string, any>>;

export function UpdateTomlMapEntryByID(arg1:models.Map):Promise<Record<string, any>>;
