// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateTileset(arg1) {
  return window['go']['mapeditor']['MapEditorApp']['CreateTileset'](arg1);
}

export function CreateTilesetImage() {
  return window['go']['mapeditor']['MapEditorApp']['CreateTilesetImage']();
}
