// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateProject(arg1) {
  return window['go']['core']['App']['CreateProject'](arg1);
}

export function GrabProjectWorkspace() {
  return window['go']['core']['App']['GrabProjectWorkspace']();
}

export function ImportProject() {
  return window['go']['core']['App']['ImportProject']();
}

export function ParseProjects() {
  return window['go']['core']['App']['ParseProjects']();
}

export function SelectProject(arg1) {
  return window['go']['core']['App']['SelectProject'](arg1);
}
