// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckOverworldId() {
  return window['go']['overworldeditor']['OverworldEditorApp']['CheckOverworldId']();
}

export function CreateOverworldFrame(arg1, arg2, arg3, arg4) {
  return window['go']['overworldeditor']['OverworldEditorApp']['CreateOverworldFrame'](arg1, arg2, arg3, arg4);
}

export function CreateOverworldTomlEntry(arg1) {
  return window['go']['overworldeditor']['OverworldEditorApp']['CreateOverworldTomlEntry'](arg1);
}

export function CreteOverworldGif(arg1, arg2, arg3, arg4) {
  return window['go']['overworldeditor']['OverworldEditorApp']['CreteOverworldGif'](arg1, arg2, arg3, arg4);
}

export function ParseOverworldData() {
  return window['go']['overworldeditor']['OverworldEditorApp']['ParseOverworldData']();
}
