// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function CheckOverworldId():Promise<number>;

export function CreateOverworldFrame(arg1:string,arg2:number,arg3:number,arg4:string):Promise<Record<string, string>>;

export function CreateOverworldTomlEntry(arg1:models.OverworldDataJson):Promise<void>;

export function CreteOverworldGif(arg1:string,arg2:number,arg3:number,arg4:string):Promise<string>;

export function ParseOverworldData():Promise<void>;
