// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GrabMusicTracks() {
  return window['go']['jukebox']['JukeboxApp']['GrabMusicTracks']();
}

export function UploadNewSong() {
  return window['go']['jukebox']['JukeboxApp']['UploadNewSong']();
}
