// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function GrabMusicTracks():Promise<Array<models.Song>>;

export function UploadNewSong():Promise<void>;
