// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function GrabAllMoves():Promise<models.AllMoves>;

export function GrabTrainerSprites():Promise<Array<models.TrainerSprite>>;

export function ParseHeldItems():Promise<Array<models.HeldItem>>;

export function ParsePokemonData():Promise<Array<models.PokemonTrainerEditor>>;

export function ParseTrainerClass():Promise<models.TrainerClasses>;

export function ParseTrainers():Promise<Array<models.TrainerJson>>;
