// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GrabAllMoves() {
  return window['go']['parsing']['ParsingApp']['GrabAllMoves']();
}

export function GrabTrainerSprites() {
  return window['go']['parsing']['ParsingApp']['GrabTrainerSprites']();
}

export function ParseHeldItems() {
  return window['go']['parsing']['ParsingApp']['ParseHeldItems']();
}

export function ParsePokemonData() {
  return window['go']['parsing']['ParsingApp']['ParsePokemonData']();
}

export function ParseTrainerClass() {
  return window['go']['parsing']['ParsingApp']['ParseTrainerClass']();
}

export function ParseTrainers() {
  return window['go']['parsing']['ParsingApp']['ParseTrainers']();
}
