// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAllMaps() {
  return window['go']['parsing']['ParsingApp']['GetAllMaps']();
}

export function GetAllTilesets() {
  return window['go']['parsing']['ParsingApp']['GetAllTilesets']();
}

export function GrabAllMoves() {
  return window['go']['parsing']['ParsingApp']['GrabAllMoves']();
}

export function GrabMusicTracks() {
  return window['go']['parsing']['ParsingApp']['GrabMusicTracks']();
}

export function GrabTrainerSprites() {
  return window['go']['parsing']['ParsingApp']['GrabTrainerSprites']();
}

export function LoadPokemonById(arg1) {
  return window['go']['parsing']['ParsingApp']['LoadPokemonById'](arg1);
}

export function ParseHeldItems() {
  return window['go']['parsing']['ParsingApp']['ParseHeldItems']();
}

export function ParseMapData(arg1) {
  return window['go']['parsing']['ParsingApp']['ParseMapData'](arg1);
}

export function ParsePokemonData() {
  return window['go']['parsing']['ParsingApp']['ParsePokemonData']();
}

export function ParseTrainerClass() {
  return window['go']['parsing']['ParsingApp']['ParseTrainerClass']();
}

export function ParseTrainers() {
  return window['go']['parsing']['ParsingApp']['ParseTrainers']();
}
