// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {parsing} from '../models';

export function GetAllMaps():Promise<Array<models.Map>>;

export function GetAllTilesets():Promise<Array<models.Tileset>>;

export function GrabAllMoves():Promise<models.AllMoves>;

export function GrabMusicTracks():Promise<Array<models.Song>>;

export function GrabTrainerSprites():Promise<Array<models.TrainerSprite>>;

export function LoadPokemonById(arg1:string):Promise<models.PokemonTrainerEditor>;

export function ParseHeldItems():Promise<Array<models.HeldItem>>;

export function ParsePokemonData():Promise<Array<parsing.OnLoadPokemonEditor>>;

export function ParseTrainerClass():Promise<models.TrainerClasses>;

export function ParseTrainers():Promise<Array<models.TrainerJson>>;
