// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function CreateTrainerData(arg1:models.TrainerJson):Promise<void>;

export function UpdateTrainer(arg1:models.TrainerJson):Promise<void>;

export function UpdateTrainerSprite():Promise<string>;
