// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateTrainerData(arg1) {
  return window['go']['trainereditor']['TrainerEditorApp']['CreateTrainerData'](arg1);
}

export function UpdateTrainer(arg1) {
  return window['go']['trainereditor']['TrainerEditorApp']['UpdateTrainer'](arg1);
}

export function UpdateTrainerSprite() {
  return window['go']['trainereditor']['TrainerEditorApp']['UpdateTrainerSprite']();
}
